### ISSUE TITLE
Add Apache project/foundation as an organisation

### ISSUE THREAD

**Issue by reginankenchor** [sustainers/academic-map#106]
Resource: https://projects.apache.org/ , https://www.apache.org/foundation/

**Comment by reginankenchor** [comment]
https://github.com/sustainers/academic-map/pull/112

**Comment by RichardLitt** [comment]
What is the difference between the two? Should we list it?

**Comment by reginankenchor** [comment]
> What is the difference between the two? Should we list it?

No, we do not have to list this again
