### ISSUE TITLE
Add Benetech as an organisation

### ISSUE THREAD

**Issue by reginankenchor** [sustainers/academic-map#107]
**Resource:** https://benetech.org/our-work/

**Comment by RichardLitt** [comment]
I'm not seeing anything here that seems related to academic open source. What am I missing? https://opensource.com/business/14/7/interview-jim-fruchterman-benetech

**Comment by reginankenchor** [comment]
> I'm not seeing anything here that seems related to academic open source. What am I missing? https://opensource.com/business/14/7/interview-jim-fruchterman-benetech

You are right, their primary focus doesn't seem to align directly with academic open source. I thought to include them due to their work with the DIAGRAM Center, particularly their efforts in developing open standards for educational content, which could have relevance to academic accessibility and open-source education. http://diagramcenter.org/about-2.html

**Comment by RichardLitt** [comment]
That seems relevant - but it's not open source work. So, I don't think it makes sense to include it at this stage. Let's try to focus on open source orgs only, not ones that are somewhat adjacent.

**Comment by reginankenchor** [comment]
> That seems relevant - but it's not open source work. So, I don't think it makes sense to include it at this stage. Let's try to focus on open source orgs only, not ones that are somewhat adjacent.

Okay
