### ISSUE TITLE
Add UW-Madison OSPO to academic map 

### ISSUE THREAD

**Issue by amkitt** [sustainers/academic-map#31]
OSPO: Yes, in the Data Science Institute.
Personnel: Kyle Cranmer, Allison Kittinger
Link: https://ospo.wisc.edu/

General Description
Thanks to a grant from the Alfred P. Sloan Foundation, The University of Wisconsin–Madison Open Source Program Office (OSPO) is positioned to support and grow our vibrant open source ecosystem. The OSPO's mission is to collaborate with key stakeholders and community members to provide open source learning opportunities, promote best practices, facilitate the use of open source software in research, and make open source–fueled connections between practitioners and adopters on campus and beyond.

Core Objectives

- Work to sustain current open source projects on campus
- Provide avenues for participation and contribution in open source software
- Facilitate partnerships to raise awareness of open source software
- Create infrastructure for starting, maintaining, sharing, and rewarding open source in research and community contexts
- Focus efforts on improving diversity, equity, and inclusion in open source

Primary Contacts
Allison Kittinger, Program Manager, Open Source Program Office

Other Context
The UW-Madison OSPO is housed within the Data Science Institute, a well-supported, campus-wide institute identified as one of UW-Madison’s Strategic Priorities. The DSI directly taps into the vibrant community using and contributing to the open source software that powers data science, and naturally has ties to other campus entities, state and local government, and industry partners. The DSI closely collaborates with the Data Science Hub, which executes a mission for community engagement and learning opportunities for campus researchers, and UW–Madison’s Libraries, which oversee Open Access strategy and are a major player in the research technologies on campus.

The UW-Madison OSPO is supported by the Alfred P. Sloan Foundation.

**Comment by RichardLitt** [comment]
Thank you, @amkitt! Apologies for missing this for so long. I've added in the content that wasn't there already.
