### ISSUE TITLE
Need a fix for typo on Universities page

### ISSUE THREAD

**Issue by CiaraFlanagan** [sustainers/academic-map#61]
Hey @RichardLitt 

No matter how much I've tried, I haven't been able to delete this '\' beside the JHU link on the [Universities page](https://sustainers.github.io/academic-map/universities.html)

Can you fix this please? 

![image](https://github.com/sustainers/academic-map/assets/101422261/b1b7a5d3-295c-409b-ad6d-5be92c50ef1f)

**Comment by RichardLitt** [comment]
Fixed!
