### ISSUE TITLE
UC Davis entry missing

### ISSUE THREAD

**Issue by CiaraFlanagan** [sustainers/academic-map#71]
Hi @RichardLitt 

I know you merged this entry: https://github.com/sustainers/academic-map/pull/65

However, it's not showing on the Jupyter book ...

![image](https://github.com/user-attachments/assets/8e400aae-dd5e-4641-87a9-83f4b8049f45)

**Comment by CiaraFlanagan** [comment]
Thanks for sharing where they were @RichardLitt

**Comment by RichardLitt** [comment]
I don't think this was completed. But it is live now.
