### ISSUE TITLE
Check re: new wording in the last paragraph of UC Santa Cruz entry

### ISSUE THREAD

**Issue by CiaraFlanagan** [sustainers/academic-map#82]
Hi Richard 

I updated the text at the end of [UC Santa Cruz's entry](https://github.com/sustainers/academic-map/blob/main/universities/university-of-california-santa-cruz.md?plain=1) to provide an update about the UC network.

I must have don't something wrong as the text is there but it didn't automatically create a pull request and the text isn't visible on the actual site.

Can you fix this?

**Comment by RichardLitt** [comment]
I am seeing it live. I think this has been fixed.
