### ISSUE TITLE
Add CURIOSS as organization

### ISSUE THREAD

**Issue by RichardLitt** [sustainers/academic-map#97]

**Comment by reginankenchor** [comment]
Hi @RichardLitt, can you assign this issue to me?

**Comment by reginankenchor** [comment]
**Resource:** https://curioss.org/about/

**Comment by RichardLitt** [comment]
Invited you as a member so you can assign yourself. :)

**Comment by reginankenchor** [comment]
> Invited you as a member so you can assign yourself. :)

Thank you!

**Comment by reginankenchor** [comment]
Pr: https://github.com/sustainers/academic-map/pull/103
